run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: false
  govet:
    enable-all: false

issues:
  exclude-dirs:
    - vendor
    - web
    - node_modules
  max-issues-per-linter: 50
  max-same-issues: 5
