import React, { useCallback, useMemo, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faCrosshairs,
  faUpload,
  faSpinner,
  faCheckCircle,
  faTriangleExclamation,
  faMagnifyingGlass,
  faFileCsv,
  faDownload,
  faRobot,
} from '@fortawesome/free-solid-svg-icons';
import { apiFetch } from '../shared/apiFetch';

// AttributionMatchDashboard — review screen for resolving Everflow click and
// conversion CSV exports back to subscriber profiles in our database.
//
// Why this page exists: the Everflow exports we get for offers like TruGreen
// have empty sub1..sub5 (the subscriber identifier was never threaded through
// the offer URL), so the only way to attribute a row to one of our users is
// to correlate IP + timestamp against mailing_tracking_events. This page
// drives the POST /api/mailing/attribution/match-csv endpoint which does
// that correlation server-side and returns matched subscriber profiles plus
// a categorized list of rows that could not be attributed.

// 1.2 — Surface upload list (mailing_lists.name + id) on every matched row.
//       Backend loadSubscriber now LEFT JOINs mailing_lists and returns
//       list_id/list_name so ops can answer "which upload seeded this
//       conversion?" without leaving the screen. Adds a "Subscribers by
//       upload list" breakdown card alongside the sending-domain card.
// 1.1 — Hardened against nil-slice JSON responses (Go encodes nil slices as
//       null which crashed `.length`); added Sending Domain breakdown card
//       and sending_domain column on the matched table.
const PAGE_VERSION = '1.2';

interface ApiSubscriber {
  subscriber_id: string;
  email: string;
  first_name?: string;
  last_name?: string;
  status?: string;
  list_id?: string;
  list_name?: string;
  created_at?: string;
  last_engaged_at?: string;
}

interface ApiMatchedRow {
  row: {
    row_index: number;
    timestamp?: string;
    click_time?: string;
    conversion_time?: string;
    ip_address?: string;
    session_user_ip?: string;
    offer_name: string;
    revenue?: number;
    transaction_id?: string;
    conversion_id?: string;
  };
  campaign_id: string;
  campaign_name?: string;
  sending_domain?: string;
  link_url?: string;
  event_at: string;
  offset_seconds: number;
  confidence_tier: 'tight' | 'fallback';
  subscriber: ApiSubscriber;
}

interface ApiUnmatchedRow {
  row: ApiMatchedRow['row'];
  reason: string;
  detail?: string;
}

interface ApiSendingDomainCount {
  sending_domain: string;
  clicks: number;
  conversions: number;
}

interface AttributionResult {
  generated_at: string;
  org_id?: string;
  window_seconds: number;
  fallback_window_hours: number;
  offer_link_pattern: string;
  total_clicks: number;
  total_conversions: number;
  matched_clicks: ApiMatchedRow[];
  unmatched_clicks: ApiUnmatchedRow[];
  matched_conversions: ApiMatchedRow[];
  unmatched_conversions: ApiUnmatchedRow[];
  unmatched_reasons: Record<string, number>;
  sending_domain_counts?: ApiSendingDomainCount[];
}

// normalizeResult coerces every array field to a real array so .length and
// .map can never throw when the backend (or a proxy) replaces a slice with
// null. Mirrors the contract written into MatchAttribution server-side; lives
// on the client too as belt-and-suspenders.
const normalizeResult = (raw: any): AttributionResult => ({
  ...raw,
  matched_clicks: Array.isArray(raw?.matched_clicks) ? raw.matched_clicks : [],
  unmatched_clicks: Array.isArray(raw?.unmatched_clicks) ? raw.unmatched_clicks : [],
  matched_conversions: Array.isArray(raw?.matched_conversions) ? raw.matched_conversions : [],
  unmatched_conversions: Array.isArray(raw?.unmatched_conversions) ? raw.unmatched_conversions : [],
  unmatched_reasons:
    raw?.unmatched_reasons && typeof raw.unmatched_reasons === 'object'
      ? raw.unmatched_reasons
      : {},
  sending_domain_counts: Array.isArray(raw?.sending_domain_counts)
    ? raw.sending_domain_counts
    : [],
});

const REASON_LABELS: Record<string, string> = {
  invalid_ip: 'Invalid IP',
  no_event_in_window: 'No click event in lookup window',
  bot_scanner_ip: 'Bot/security scanner IP',
  outside_retention: 'Outside retention window',
  subscriber_missing: 'Subscriber record no longer exists',
  db_error: 'Lookup error',
};

const REASON_HINTS: Record<string, string> = {
  bot_scanner_ip:
    'Microsoft Defender, Outlook Safe Links, Apple Mail Privacy Protection, etc. These click events were generated by an email security scanner — not a real subscriber.',
  no_event_in_window:
    'No recorded click matched this IP and time on an offer link. Most often means the click came from a session not driven by our email (organic, retargeting, etc.).',
  invalid_ip: 'IP could not be parsed.',
  subscriber_missing: 'A click was recorded but the subscriber record was permanently deleted.',
  db_error: 'A lookup error occurred. Please try again or contact support.',
};

const fmtPct = (num: number, total: number): string => {
  if (!total) return '—';
  return `${Math.round((num / total) * 100)}%`;
};

const fmtTime = (s?: string): string => {
  if (!s) return '—';
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return s;
  return d.toLocaleString();
};

const tierColor = (tier: string): string => {
  if (tier === 'tight') return '#22c55e';
  if (tier === 'fallback') return '#f59e0b';
  return '#64748b';
};

export const AttributionMatchDashboard: React.FC = () => {
  const [clicksFile, setClicksFile] = useState<File | null>(null);
  const [conversionsFile, setConversionsFile] = useState<File | null>(null);
  const [offerPattern, setOfferPattern] = useState('%trugreen%');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AttributionResult | null>(null);
  const [activeTab, setActiveTab] = useState<'matched' | 'unmatched'>('matched');

  const canSubmit = !!(clicksFile || conversionsFile) && !loading;

  const handleSubmit = useCallback(async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const fd = new FormData();
      if (clicksFile) fd.append('clicks', clicksFile);
      if (conversionsFile) fd.append('conversions', conversionsFile);
      if (offerPattern.trim()) fd.append('offer_pattern', offerPattern.trim());

      const resp = await apiFetch('/api/mailing/attribution/match-csv', {
        method: 'POST',
        body: fd,
        credentials: 'include',
      });
      if (!resp.ok) {
        const body = await resp.json().catch(() => ({}));
        throw new Error(body.detail || body.error || `HTTP ${resp.status}`);
      }
      const raw = await resp.json();
      const data = normalizeResult(raw);
      setResult(data);
      setActiveTab(
        data.matched_clicks.length > 0 || data.matched_conversions.length > 0
          ? 'matched'
          : 'unmatched',
      );
    } catch (e: any) {
      setError(e?.message || String(e));
    } finally {
      setLoading(false);
    }
  }, [clicksFile, conversionsFile, offerPattern]);

  const handleDownload = useCallback(() => {
    if (!result) return;
    const blob = new Blob([JSON.stringify(result, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `attribution-match-${new Date().toISOString().replace(/[:.]/g, '-')}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [result]);

  const totals = useMemo(() => {
    if (!result) return null;
    return {
      clicksMatched: result.matched_clicks.length,
      clicksTotal: result.total_clicks,
      conversionsMatched: result.matched_conversions.length,
      conversionsTotal: result.total_conversions,
    };
  }, [result]);

  return (
    <div style={pageStyle}>
      <header style={headerStyle}>
        <div>
          <h1 style={{ margin: 0, fontSize: 22, color: '#e2e8f0', fontWeight: 600 }}>
            <FontAwesomeIcon icon={faCrosshairs} style={{ marginRight: 10, color: '#818cf8' }} />
            Attribution Match
          </h1>
          <div style={{ color: 'rgba(180,210,240,0.65)', fontSize: 12, marginTop: 4 }}>
            Resolve offer tracking click and conversion CSVs back to subscriber profiles
          </div>
        </div>
        <div style={{ fontSize: 11, color: 'rgba(180,210,240,0.45)' }}>v{PAGE_VERSION}</div>
      </header>

      <section style={cardStyle}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <FileSlot
            label="Offer Tracking Clicks CSV"
            placeholder="trugreen-clicks.csv"
            file={clicksFile}
            onChange={setClicksFile}
          />
          <FileSlot
            label="Offer Tracking Conversions CSV"
            placeholder="trugreen-ConversionsExport_*.csv"
            file={conversionsFile}
            onChange={setConversionsFile}
          />
        </div>

        <div style={{ display: 'flex', gap: 12, marginTop: 16, alignItems: 'flex-end', flexWrap: 'wrap' }}>
          <label style={{ display: 'flex', flexDirection: 'column', gap: 6, flex: '1 1 280px' }}>
            <span style={{ fontSize: 11, color: 'rgba(180,210,240,0.7)' }}>
              Offer link pattern (match)
            </span>
            <input
              type="text"
              value={offerPattern}
              onChange={(e) => setOfferPattern(e.target.value)}
              placeholder="%trugreen%"
              style={inputStyle}
            />
          </label>
          <button
            onClick={handleSubmit}
            disabled={!canSubmit}
            style={{
              ...primaryButton,
              opacity: canSubmit ? 1 : 0.5,
              cursor: canSubmit ? 'pointer' : 'not-allowed',
            }}
          >
            {loading ? (
              <>
                <FontAwesomeIcon icon={faSpinner} spin style={{ marginRight: 8 }} />
                Matching…
              </>
            ) : (
              <>
                <FontAwesomeIcon icon={faMagnifyingGlass} style={{ marginRight: 8 }} />
                Match Attribution
              </>
            )}
          </button>
        </div>

        {error && (
          <div style={errorBanner}>
            <FontAwesomeIcon icon={faTriangleExclamation} style={{ marginRight: 8 }} />
            {error}
          </div>
        )}
      </section>

      {result && totals && (
        <>
          <section style={{ ...cardStyle, marginTop: 16 }}>
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
                gap: 12,
              }}
            >
              <Counter
                label="Clicks matched"
                value={`${totals.clicksMatched} / ${totals.clicksTotal}`}
                pct={fmtPct(totals.clicksMatched, totals.clicksTotal)}
                color="#22c55e"
              />
              <Counter
                label="Conversions matched"
                value={`${totals.conversionsMatched} / ${totals.conversionsTotal}`}
                pct={fmtPct(totals.conversionsMatched, totals.conversionsTotal)}
                color="#22c55e"
              />
              <Counter
                label="Tight window"
                value={`±${result.window_seconds}s`}
                pct={`fallback ±${result.fallback_window_hours}h`}
                color="#818cf8"
              />
              <Counter
                label="Offer pattern"
                value={result.offer_link_pattern}
                pct=""
                color="#f59e0b"
              />
            </div>

            {Object.keys(result.unmatched_reasons).length > 0 && (
              <div style={{ marginTop: 14, display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                {Object.entries(result.unmatched_reasons).map(([k, v]) => (
                  <span key={k} style={chipStyle} title={REASON_HINTS[k] || ''}>
                    <strong style={{ color: '#f59e0b' }}>{v}</strong>{' '}
                    <span style={{ color: 'rgba(180,210,240,0.65)' }}>
                      {REASON_LABELS[k] || k}
                    </span>
                  </span>
                ))}
              </div>
            )}

            <div style={{ marginTop: 14, textAlign: 'right' }}>
              <button onClick={handleDownload} style={secondaryButton}>
                <FontAwesomeIcon icon={faDownload} style={{ marginRight: 8 }} />
                Download JSON
              </button>
            </div>
          </section>

          <SendingDomainBreakdown counts={result.sending_domain_counts ?? []} />
          <UploadListBreakdown
            matchedClicks={result.matched_clicks}
            matchedConversions={result.matched_conversions}
          />


          <section style={{ ...cardStyle, marginTop: 16, padding: 0, overflow: 'hidden' }}>
            <div style={tabBarStyle}>
              <TabButton
                active={activeTab === 'matched'}
                onClick={() => setActiveTab('matched')}
                count={totals.clicksMatched + totals.conversionsMatched}
                label="Matched"
                color="#22c55e"
              />
              <TabButton
                active={activeTab === 'unmatched'}
                onClick={() => setActiveTab('unmatched')}
                count={
                  result.unmatched_clicks.length + result.unmatched_conversions.length
                }
                label="Unmatched"
                color="#f59e0b"
              />
            </div>

            {activeTab === 'matched' ? (
              <MatchedTables result={result} />
            ) : (
              <UnmatchedTables result={result} />
            )}
          </section>
        </>
      )}

      {!result && !loading && (
        <section style={{ ...cardStyle, marginTop: 16, color: 'rgba(180,210,240,0.65)', fontSize: 13 }}>
          <FontAwesomeIcon icon={faRobot} style={{ marginRight: 8, color: '#818cf8' }} />
          Drop the offer tracking click and conversion exports above. We correlate each row's IP and
          timestamp against your recorded email clicks, look for a matching click on a link that
          fits the offer pattern, then pull the matching subscriber profile. Rows that do not
          match (email security scanners, missing click records, expired retention) are listed with
          a reason so you can confirm them by hand.
        </section>
      )}
    </div>
  );
};

// ---------- Sub-components ----------

interface FileSlotProps {
  label: string;
  placeholder: string;
  file: File | null;
  onChange: (f: File | null) => void;
}

const FileSlot: React.FC<FileSlotProps> = ({ label, placeholder, file, onChange }) => {
  const inputId = `file-${label.replace(/\s+/g, '-').toLowerCase()}`;
  return (
    <label htmlFor={inputId} style={fileSlotStyle}>
      <input
        id={inputId}
        type="file"
        accept=".csv,text/csv"
        onChange={(e) => onChange(e.target.files?.[0] ?? null)}
        style={{ display: 'none' }}
      />
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        <FontAwesomeIcon
          icon={file ? faFileCsv : faUpload}
          style={{ fontSize: 22, color: file ? '#22c55e' : '#818cf8' }}
        />
        <div>
          <div style={{ fontSize: 12, color: 'rgba(180,210,240,0.7)' }}>{label}</div>
          <div style={{ fontSize: 14, color: '#e2e8f0', marginTop: 2 }}>
            {file ? file.name : <span style={{ opacity: 0.5 }}>{placeholder}</span>}
          </div>
          {file && (
            <div style={{ fontSize: 11, color: 'rgba(180,210,240,0.5)', marginTop: 2 }}>
              {(file.size / 1024).toFixed(1)} KB
            </div>
          )}
        </div>
      </div>
    </label>
  );
};

const Counter: React.FC<{ label: string; value: string; pct: string; color: string }> = ({
  label,
  value,
  pct,
  color,
}) => (
  <div style={counterStyle}>
    <div style={{ fontSize: 11, color: 'rgba(180,210,240,0.6)', textTransform: 'uppercase', letterSpacing: 0.5 }}>
      {label}
    </div>
    <div style={{ fontSize: 20, color: '#e2e8f0', fontWeight: 600, marginTop: 4 }}>
      {value}
    </div>
    {pct && (
      <div style={{ fontSize: 12, color, marginTop: 2 }}>{pct}</div>
    )}
  </div>
);

const TabButton: React.FC<{
  active: boolean;
  onClick: () => void;
  count: number;
  label: string;
  color: string;
}> = ({ active, onClick, count, label, color }) => (
  <button
    onClick={onClick}
    style={{
      ...tabButtonStyle,
      borderBottomColor: active ? color : 'transparent',
      color: active ? '#e2e8f0' : 'rgba(180,210,240,0.6)',
    }}
  >
    <FontAwesomeIcon
      icon={label === 'Matched' ? faCheckCircle : faTriangleExclamation}
      style={{ marginRight: 8, color }}
    />
    {label} <span style={{ marginLeft: 6, color }}>{count}</span>
  </button>
);

// SendingDomainBreakdown shows which sending infrastructure produced the
// matched clicks and conversions. Sorted server-side by clicks desc; we
// just render the first 12 rows with bars normalized to the top click
// count so it's easy to eyeball relative volume across brands.
const SendingDomainBreakdown: React.FC<{ counts: ApiSendingDomainCount[] }> = ({ counts }) => {
  if (!counts || counts.length === 0) return null;
  const max = Math.max(...counts.map((c) => c.clicks), 1);
  const totalClicks = counts.reduce((sum, c) => sum + c.clicks, 0);
  const totalConv = counts.reduce((sum, c) => sum + c.conversions, 0);
  const top = counts.slice(0, 12);
  return (
    <section style={{ ...cardStyle, marginTop: 16 }}>
      <div
        style={{
          display: 'flex',
          alignItems: 'baseline',
          justifyContent: 'space-between',
          marginBottom: 12,
        }}
      >
        <h3 style={{ ...tableTitleStyle, margin: 0 }}>Clicks by sending domain</h3>
        <div style={{ fontSize: 11, color: 'rgba(180,210,240,0.6)' }}>
          {counts.length} domain{counts.length === 1 ? '' : 's'} · {totalClicks} click
          {totalClicks === 1 ? '' : 's'} · {totalConv} conversion{totalConv === 1 ? '' : 's'}
        </div>
      </div>
      <table style={tableStyle}>
        <thead>
          <tr style={trHeaderStyle}>
            <th style={thStyle}>Sending domain</th>
            <th style={{ ...thStyle, width: '45%' }}>Clicks</th>
            <th style={{ ...thStyle, textAlign: 'right' }}>Conversions</th>
            <th style={{ ...thStyle, textAlign: 'right' }}>Share</th>
          </tr>
        </thead>
        <tbody>
          {top.map((c) => {
            const share = totalClicks > 0 ? (c.clicks / totalClicks) * 100 : 0;
            const barPct = (c.clicks / max) * 100;
            return (
              <tr key={c.sending_domain} style={trBodyStyle}>
                <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 12 }}>
                  {c.sending_domain}
                </td>
                <td style={tdStyle}>
                  <div
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 8,
                    }}
                  >
                    <div
                      style={{
                        flex: 1,
                        height: 8,
                        background: 'rgba(99, 102, 241, 0.12)',
                        borderRadius: 4,
                        overflow: 'hidden',
                      }}
                    >
                      <div
                        style={{
                          width: `${barPct}%`,
                          height: '100%',
                          background:
                            'linear-gradient(90deg, #6366f1 0%, #818cf8 100%)',
                        }}
                      />
                    </div>
                    <span
                      style={{
                        minWidth: 36,
                        textAlign: 'right',
                        fontFamily: 'monospace',
                        fontSize: 12,
                      }}
                    >
                      {c.clicks}
                    </span>
                  </div>
                </td>
                <td
                  style={{
                    ...tdStyle,
                    textAlign: 'right',
                    fontFamily: 'monospace',
                    fontSize: 12,
                    color: c.conversions > 0 ? '#22c55e' : 'rgba(180,210,240,0.5)',
                  }}
                >
                  {c.conversions}
                </td>
                <td
                  style={{
                    ...tdStyle,
                    textAlign: 'right',
                    fontFamily: 'monospace',
                    fontSize: 12,
                    color: 'rgba(180,210,240,0.65)',
                  }}
                >
                  {share.toFixed(1)}%
                </td>
              </tr>
            );
          })}
          {counts.length > top.length && (
            <tr style={trBodyStyle}>
              <td colSpan={4} style={{ ...tdStyle, color: 'rgba(180,210,240,0.5)', fontSize: 12 }}>
                +{counts.length - top.length} more domain
                {counts.length - top.length === 1 ? '' : 's'} hidden — full list in the JSON
                download.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </section>
  );
};

// UploadListBreakdown rolls matched rows up by mailing_lists.name (sourced
// from the subscriber's list_id). Computed client-side from the matched
// arrays so we don't add a backend round-trip; the matched arrays are
// already loaded and capped, so this is cheap. Subscribers with no list
// (legacy rows or import-time orphans) bucket as "(no upload list)".
const UploadListBreakdown: React.FC<{
  matchedClicks: ApiMatchedRow[];
  matchedConversions: ApiMatchedRow[];
}> = ({ matchedClicks, matchedConversions }) => {
  const tally = useMemo(() => {
    type Bucket = {
      key: string;
      listName: string;
      listID: string;
      clicks: number;
      conversions: number;
    };
    const map = new Map<string, Bucket>();
    const bump = (m: ApiMatchedRow, kind: 'click' | 'conversion') => {
      const listID = m.subscriber?.list_id || '';
      const listName = m.subscriber?.list_name || '';
      const key = listID || `(name:${listName || '(no upload list)'})`;
      let b = map.get(key);
      if (!b) {
        b = {
          key,
          listName: listName || '(no upload list)',
          listID,
          clicks: 0,
          conversions: 0,
        };
        map.set(key, b);
      }
      if (kind === 'click') b.clicks += 1;
      else b.conversions += 1;
    };
    matchedClicks.forEach((m) => bump(m, 'click'));
    matchedConversions.forEach((m) => bump(m, 'conversion'));
    return Array.from(map.values()).sort((a, b) => {
      if (b.clicks !== a.clicks) return b.clicks - a.clicks;
      return b.conversions - a.conversions;
    });
  }, [matchedClicks, matchedConversions]);

  if (tally.length === 0) return null;
  const max = Math.max(...tally.map((b) => b.clicks), 1);
  const totalClicks = tally.reduce((s, b) => s + b.clicks, 0);
  const totalConv = tally.reduce((s, b) => s + b.conversions, 0);
  const top = tally.slice(0, 12);

  return (
    <section style={{ ...cardStyle, marginTop: 16 }}>
      <div
        style={{
          display: 'flex',
          alignItems: 'baseline',
          justifyContent: 'space-between',
          marginBottom: 12,
        }}
      >
        <h3 style={{ ...tableTitleStyle, margin: 0 }}>Matched subscribers by upload list</h3>
        <div style={{ fontSize: 11, color: 'rgba(180,210,240,0.6)' }}>
          {tally.length} list{tally.length === 1 ? '' : 's'} · {totalClicks} click
          {totalClicks === 1 ? '' : 's'} · {totalConv} conversion{totalConv === 1 ? '' : 's'}
        </div>
      </div>
      <table style={tableStyle}>
        <thead>
          <tr style={trHeaderStyle}>
            <th style={thStyle}>Upload list</th>
            <th style={{ ...thStyle, width: '45%' }}>Clicks</th>
            <th style={{ ...thStyle, textAlign: 'right' }}>Conversions</th>
            <th style={{ ...thStyle, textAlign: 'right' }}>Share</th>
          </tr>
        </thead>
        <tbody>
          {top.map((b) => {
            const share = totalClicks > 0 ? (b.clicks / totalClicks) * 100 : 0;
            const barPct = (b.clicks / max) * 100;
            return (
              <tr key={b.key} style={trBodyStyle}>
                <td style={{ ...tdStyle, fontSize: 12 }}>
                  <div style={{ display: 'flex', flexDirection: 'column' }}>
                    <span style={{ color: '#e2e8f0' }}>{b.listName}</span>
                    {b.listID && (
                      <span
                        style={{
                          color: 'rgba(180,210,240,0.4)',
                          fontFamily: 'monospace',
                          fontSize: 10,
                        }}
                      >
                        {b.listID.slice(0, 8)}
                      </span>
                    )}
                  </div>
                </td>
                <td style={tdStyle}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <div
                      style={{
                        flex: 1,
                        height: 6,
                        borderRadius: 3,
                        background: 'rgba(56,189,248,0.15)',
                        overflow: 'hidden',
                      }}
                    >
                      <div
                        style={{
                          width: `${barPct}%`,
                          height: '100%',
                          background: '#22d3ee',
                        }}
                      />
                    </div>
                    <strong style={{ minWidth: 36, textAlign: 'right' }}>{b.clicks}</strong>
                  </div>
                </td>
                <td style={{ ...tdStyle, textAlign: 'right', color: '#22c55e' }}>
                  {b.conversions}
                </td>
                <td style={{ ...tdStyle, textAlign: 'right', color: 'rgba(180,210,240,0.7)' }}>
                  {share.toFixed(1)}%
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </section>
  );
};

const MatchedTables: React.FC<{ result: AttributionResult }> = ({ result }) => (
  <div>
    {result.matched_clicks.length > 0 && (
      <MatchedTable
        title={`Matched clicks (${result.matched_clicks.length})`}
        rows={result.matched_clicks}
        kind="click"
      />
    )}
    {result.matched_conversions.length > 0 && (
      <MatchedTable
        title={`Matched conversions (${result.matched_conversions.length})`}
        rows={result.matched_conversions}
        kind="conversion"
      />
    )}
    {result.matched_clicks.length === 0 && result.matched_conversions.length === 0 && (
      <EmptyState text="No rows matched. Check the unmatched tab for reasons." />
    )}
  </div>
);

const UnmatchedTables: React.FC<{ result: AttributionResult }> = ({ result }) => (
  <div>
    {result.unmatched_clicks.length > 0 && (
      <UnmatchedTable
        title={`Unmatched clicks (${result.unmatched_clicks.length})`}
        rows={result.unmatched_clicks}
        kind="click"
      />
    )}
    {result.unmatched_conversions.length > 0 && (
      <UnmatchedTable
        title={`Unmatched conversions (${result.unmatched_conversions.length})`}
        rows={result.unmatched_conversions}
        kind="conversion"
      />
    )}
    {result.unmatched_clicks.length === 0 && result.unmatched_conversions.length === 0 && (
      <EmptyState text="Every row matched. Nice." />
    )}
  </div>
);

const MatchedTable: React.FC<{
  title: string;
  rows: ApiMatchedRow[];
  kind: 'click' | 'conversion';
}> = ({ title, rows, kind }) => (
  <div style={{ padding: 16 }}>
    <h3 style={tableTitleStyle}>{title}</h3>
    <div style={{ overflowX: 'auto' }}>
      <table style={tableStyle}>
        <thead>
          <tr style={trHeaderStyle}>
            <th style={thStyle}>#</th>
            <th style={thStyle}>Click time (UTC)</th>
            <th style={thStyle}>IP</th>
            <th style={thStyle}>Tier</th>
            <th style={thStyle}>Δ (s)</th>
            <th style={thStyle}>Sending domain</th>
            <th style={thStyle} title="Upload list the subscriber was originally imported into.">Upload list</th>
            <th style={thStyle}>Email</th>
            <th style={thStyle}>Subscriber ID</th>
            <th style={thStyle}>Campaign</th>
            {kind === 'conversion' && <th style={{ ...thStyle, textAlign: 'right' }}>Revenue</th>}
          </tr>
        </thead>
        <tbody>
          {rows.map((m, i) => {
            const ts = kind === 'click' ? m.row.timestamp : m.row.click_time;
            const ip = kind === 'click' ? m.row.ip_address : m.row.session_user_ip;
            const sendingDomain = m.sending_domain && m.sending_domain.length > 0 ? m.sending_domain : '—';
            const subId = m.subscriber?.subscriber_id ?? '';
            const listName = m.subscriber?.list_name && m.subscriber.list_name.length > 0
              ? m.subscriber.list_name
              : '—';
            return (
              <tr key={i} style={trBodyStyle}>
                <td style={tdStyle}>{m.row.row_index}</td>
                <td style={tdStyle}>{fmtTime(ts)}</td>
                <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 12 }}>{ip}</td>
                <td style={tdStyle}>
                  <span
                    style={{
                      background: `${tierColor(m.confidence_tier)}22`,
                      color: tierColor(m.confidence_tier),
                      padding: '2px 8px',
                      borderRadius: 4,
                      fontSize: 11,
                      textTransform: 'uppercase',
                    }}
                  >
                    {m.confidence_tier}
                  </span>
                </td>
                <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 12 }}>
                  {m.offset_seconds}
                </td>
                <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 12 }}>
                  {sendingDomain}
                </td>
                <td
                  style={{ ...tdStyle, fontSize: 12, maxWidth: 220, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}
                  title={m.subscriber?.list_name || ''}
                >
                  {listName}
                </td>
                <td style={tdStyle}>{m.subscriber?.email || '—'}</td>
                <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 11, color: 'rgba(180,210,240,0.6)' }}>
                  {subId ? subId.slice(0, 8) : '—'}
                </td>
                <td style={tdStyle}>{m.campaign_name || (m.campaign_id ? m.campaign_id.slice(0, 8) : '—')}</td>
                {kind === 'conversion' && (
                  <td style={{ ...tdStyle, textAlign: 'right', color: '#22c55e' }}>
                    ${(m.row.revenue ?? 0).toFixed(2)}
                  </td>
                )}
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  </div>
);

const UnmatchedTable: React.FC<{
  title: string;
  rows: ApiUnmatchedRow[];
  kind: 'click' | 'conversion';
}> = ({ title, rows, kind }) => (
  <div style={{ padding: 16 }}>
    <h3 style={tableTitleStyle}>{title}</h3>
    <div style={{ overflowX: 'auto' }}>
      <table style={tableStyle}>
        <thead>
          <tr style={trHeaderStyle}>
            <th style={thStyle}>#</th>
            <th style={thStyle}>Time (UTC)</th>
            <th style={thStyle}>IP</th>
            <th style={thStyle}>Reason</th>
            <th style={thStyle}>Detail</th>
            {kind === 'conversion' && <th style={{ ...thStyle, textAlign: 'right' }}>Revenue</th>}
          </tr>
        </thead>
        <tbody>
          {rows.map((u, i) => {
            const ts = kind === 'click' ? u.row.timestamp : u.row.click_time;
            const ip = kind === 'click' ? u.row.ip_address : u.row.session_user_ip;
            return (
              <tr key={i} style={trBodyStyle}>
                <td style={tdStyle}>{u.row.row_index}</td>
                <td style={tdStyle}>{fmtTime(ts)}</td>
                <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 12 }}>{ip}</td>
                <td style={tdStyle}>
                  <span style={reasonChip(u.reason)} title={REASON_HINTS[u.reason] || u.reason}>
                    {REASON_LABELS[u.reason] || u.reason}
                  </span>
                </td>
                <td style={{ ...tdStyle, color: 'rgba(180,210,240,0.65)', fontSize: 12 }}>
                  {u.detail || '—'}
                </td>
                {kind === 'conversion' && (
                  <td style={{ ...tdStyle, textAlign: 'right', color: '#f59e0b' }}>
                    ${(u.row.revenue ?? 0).toFixed(2)}
                  </td>
                )}
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  </div>
);

const EmptyState: React.FC<{ text: string }> = ({ text }) => (
  <div style={{ padding: 32, textAlign: 'center', color: 'rgba(180,210,240,0.6)', fontSize: 13 }}>
    {text}
  </div>
);

// ---------- Styles ----------

const pageStyle: React.CSSProperties = {
  padding: 24,
  background: 'linear-gradient(180deg, #0a0e1a 0%, #0f1424 100%)',
  minHeight: '100%',
  color: '#e2e8f0',
};

const headerStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginBottom: 16,
};

const cardStyle: React.CSSProperties = {
  background: 'rgba(15, 23, 42, 0.6)',
  border: '1px solid rgba(99, 102, 241, 0.18)',
  borderRadius: 8,
  padding: 16,
};

const fileSlotStyle: React.CSSProperties = {
  display: 'block',
  padding: 14,
  background: 'rgba(30, 41, 59, 0.5)',
  border: '1px dashed rgba(99, 102, 241, 0.3)',
  borderRadius: 6,
  cursor: 'pointer',
};

const inputStyle: React.CSSProperties = {
  background: 'rgba(15, 23, 42, 0.7)',
  border: '1px solid rgba(99, 102, 241, 0.25)',
  color: '#e2e8f0',
  padding: '8px 10px',
  borderRadius: 4,
  fontSize: 13,
  fontFamily: 'monospace',
};

const primaryButton: React.CSSProperties = {
  background: 'linear-gradient(135deg, #6366f1 0%, #818cf8 100%)',
  color: '#fff',
  border: 'none',
  padding: '10px 18px',
  borderRadius: 6,
  fontWeight: 600,
  fontSize: 13,
};

const secondaryButton: React.CSSProperties = {
  background: 'rgba(99, 102, 241, 0.15)',
  color: '#a5b4fc',
  border: '1px solid rgba(99, 102, 241, 0.3)',
  padding: '8px 14px',
  borderRadius: 6,
  fontSize: 12,
  cursor: 'pointer',
};

const errorBanner: React.CSSProperties = {
  marginTop: 14,
  padding: 12,
  background: 'rgba(239, 68, 68, 0.1)',
  border: '1px solid rgba(239, 68, 68, 0.3)',
  borderRadius: 4,
  color: '#fca5a5',
  fontSize: 13,
};

const counterStyle: React.CSSProperties = {
  background: 'rgba(15, 23, 42, 0.7)',
  border: '1px solid rgba(99, 102, 241, 0.15)',
  borderRadius: 6,
  padding: 12,
};

const chipStyle: React.CSSProperties = {
  background: 'rgba(245, 158, 11, 0.1)',
  border: '1px solid rgba(245, 158, 11, 0.25)',
  padding: '4px 10px',
  borderRadius: 4,
  fontSize: 12,
};

const tabBarStyle: React.CSSProperties = {
  display: 'flex',
  borderBottom: '1px solid rgba(99, 102, 241, 0.15)',
  background: 'rgba(10, 14, 26, 0.5)',
};

const tabButtonStyle: React.CSSProperties = {
  background: 'transparent',
  border: 'none',
  borderBottom: '2px solid transparent',
  padding: '12px 18px',
  fontSize: 13,
  fontWeight: 500,
  cursor: 'pointer',
  transition: 'all 0.15s',
};

const tableTitleStyle: React.CSSProperties = {
  margin: '0 0 12px 0',
  fontSize: 13,
  color: '#e2e8f0',
  fontWeight: 600,
  textTransform: 'uppercase',
  letterSpacing: 0.5,
};

const tableStyle: React.CSSProperties = {
  width: '100%',
  borderCollapse: 'collapse',
  fontSize: 13,
};

const trHeaderStyle: React.CSSProperties = {
  background: 'rgba(99, 102, 241, 0.08)',
};

const trBodyStyle: React.CSSProperties = {
  borderBottom: '1px solid rgba(99, 102, 241, 0.08)',
};

const thStyle: React.CSSProperties = {
  textAlign: 'left',
  padding: '10px 12px',
  fontSize: 11,
  textTransform: 'uppercase',
  letterSpacing: 0.5,
  color: 'rgba(180,210,240,0.7)',
  fontWeight: 600,
};

const tdStyle: React.CSSProperties = {
  padding: '10px 12px',
  color: '#e2e8f0',
};

function reasonChip(reason: string): React.CSSProperties {
  const palette: Record<string, [string, string]> = {
    bot_scanner_ip: ['rgba(168, 85, 247, 0.12)', '#c4b5fd'],
    no_event_in_window: ['rgba(245, 158, 11, 0.1)', '#fcd34d'],
    invalid_ip: ['rgba(239, 68, 68, 0.1)', '#fca5a5'],
    db_error: ['rgba(239, 68, 68, 0.18)', '#fca5a5'],
    subscriber_missing: ['rgba(100, 116, 139, 0.15)', '#cbd5e1'],
    outside_retention: ['rgba(100, 116, 139, 0.15)', '#cbd5e1'],
  };
  const [bg, fg] = palette[reason] || ['rgba(100, 116, 139, 0.15)', '#cbd5e1'];
  return {
    background: bg,
    color: fg,
    padding: '3px 8px',
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 500,
  };
}
